spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ikea-database.cnukdrbce1d7.ap-northeast-2.rds.amazonaws.com:3306/ikea
    username: root
    password: 12345678
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      location: /home/ubuntu/ikea/src/main/resources/static/img
      max-file-size: 200MB
      max-request-size: 100MB
  # redis config
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: ec2-3-39-25-140.ap-northeast-2.compute.amazonaws.com
    port: 6379
    password: "1234"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          # 사용자 인증 시도 여부(default = false)
          auth: true
          # Socket read timeout 5000ms(default = 무한)
          timeout: 5000
          # startTLS 활성화 여부(default = false)
          starttls:
            enable: true
mybatis:
  type-aliases-package: com.ikea.entity
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    root: info
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ikea
    username: root
    password: 1234
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      location: C:\dev\project\ikea\src\main\resources\static\img
      max-file-size: 200MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          # 사용자 인증 시도 여부(default = false)
          auth: true
          # Socket read timeout 5000ms(default = 무한)
          timeout: 5000
          # startTLS 활성화 여부(default = false)
          starttls:
            enable: true
logging:
  level:
    root: debug
